### PR TITLE
Authentication

### PR DESCRIPTION
**Pull request by Niedzwiedz**
This change is [Reviewable](https://reviewable.io/reviews/niedzwiedz/montekombat/3)

### CODE REVIEW

**Comment by jotka87** [comment]
Reviewed 15 of 17 files at r1.
Review status: 15 of 17 files reviewed at latest revision, 8 unresolved discussions.

---

_[app/controllers/sessions_controller.rb, line 11 at r1](https://reviewable.io:443/reviews/niedzwiedz/montekombat/3#-KRmyGR7zL1MON6VZ2tU:-KRmyGR7zL1MON6VZ2tV:b-4vew5k) ([raw file](https://github.com/niedzwiedz/montekombat/blob/7154ff8074fe92e365a948fa92068406d59eb3d0/app/controllers/sessions_controller.rb#L11)):_

> ``` Ruby
> 
>     else
>       flash[:error] = "This account doesn't exist"
> ```

Not entirely - password could be wrong also.

---

_[app/controllers/users_controller.rb, line 3 at r1](https://reviewable.io:443/reviews/niedzwiedz/montekombat/3#-KRmyh0TYGGS3Z1uzu-y:-KRmyh0TYGGS3Z1uzu-z:b-d9yi33) ([raw file](https://github.com/niedzwiedz/montekombat/blob/7154ff8074fe92e365a948fa92068406d59eb3d0/app/controllers/users_controller.rb#L3)):_

> ``` Ruby
> class UsersController < ApplicationController
>   # CALY CRUD, jak bedzie admin to beda zmiany
>   # Widoki sa spartanskie ale dzialaja
> ```

It's good you're adding those comments but please - all in English :)

---

_[app/views/users/edit.html.slim, line 5 at r1](https://reviewable.io:443/reviews/niedzwiedz/montekombat/3#-KRmzbnG8z0VZzxhJqkM:-KRmzbnHbXXWwf2UjT4-:b-m368cw) ([raw file](https://github.com/niedzwiedz/montekombat/blob/7154ff8074fe92e365a948fa92068406d59eb3d0/app/views/users/edit.html.slim#L5)):_

> ``` Slim
>   ul
>     - @user.errors.full_messages.each do |msg|
>       li= msg
> ```

you're already displaying errors in matches in similar way, it would be good to move it to a partial and render it wherever errors are displayed

---

_[app/views/users/index.html.slim, line 20 at r1](https://reviewable.io:443/reviews/niedzwiedz/montekombat/3#-KRmzxdXGQzUGhi8dYiv:-KRmzxdXGQzUGhi8dYiw:b-gad219) ([raw file](https://github.com/niedzwiedz/montekombat/blob/7154ff8074fe92e365a948fa92068406d59eb3d0/app/views/users/index.html.slim#L20)):_

> ``` Slim
>           = link_to "show", user
>         td
>           = link_to "edit", edit_user_path(user)
> ```

we shouldn't be able to edit other user's account

---

_[app/views/users/index.html.slim, line 22 at r1](https://reviewable.io:443/reviews/niedzwiedz/montekombat/3#-KRn-1_amdgrlx7TW0aj:-KRn-1_amdgrlx7TW0ak:bohlubw) ([raw file](https://github.com/niedzwiedz/montekombat/blob/7154ff8074fe92e365a948fa92068406d59eb3d0/app/views/users/index.html.slim#L22)):_

> ``` Slim
>           = link_to "edit", edit_user_path(user)
>         td
>           = link_to "delete", user, method: :delete, data: { confirm: "You sure?" }
> ```

same with that

---

_[app/views/users/new.html.slim, line 26 at r1](https://reviewable.io:443/reviews/niedzwiedz/montekombat/3#-KRn-8D25DDH6j12-nFe:-KRn-8D25DDH6j12-nFf:bgukwgf) ([raw file](https://github.com/niedzwiedz/montekombat/blob/7154ff8074fe92e365a948fa92068406d59eb3d0/app/views/users/new.html.slim#L26)):_

> ``` Slim
>   = f.label :password
>   | :
>   = f.password_field :password
> ```

what about password confirmation?

---

_[config/routes.rb, line 1 at r1](https://reviewable.io:443/reviews/niedzwiedz/montekombat/3#-KRn29JlMbdmgmGk3yPE:-KRn29Jm7jXayT2LGu2Q:b1c5385) ([raw file](https://github.com/niedzwiedz/montekombat/blob/7154ff8074fe92e365a948fa92068406d59eb3d0/config/routes.rb#L1)):_

> ``` Ruby
> Rails.application.routes.draw do
> ```

please specify root also

---

_[config/routes.rb, line 6 at r1](https://reviewable.io:443/reviews/niedzwiedz/montekombat/3#-KRn1TjTa4MXF0cKBZjN:-KRn1TjUtICTwDOB8ooS:bq6dgny) ([raw file](https://github.com/niedzwiedz/montekombat/blob/7154ff8074fe92e365a948fa92068406d59eb3d0/config/routes.rb#L6)):_

> ``` Ruby
>   get "/signup", to: "users#new"
>   get "/login", to: "sessions#new"
>   post "/login", to: "sessions#create"
> ```

why this one?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/niedzwiedz/montekombat/3)_

**Comment by jotka87** [comment]
Reviewed 6 of 8 files at r2.
Review status: 17 of 19 files reviewed at latest revision, 6 unresolved discussions.

---

_[app/controllers/sessions_controller.rb, line 19 at r2](https://reviewable.io:443/reviews/niedzwiedz/montekombat/3#-KS0R128kM8KHXBeSAPo:-KS0R128kM8KHXBeSAPp:bl90dix) ([raw file](https://github.com/niedzwiedz/montekombat/blob/6b835e18f43c8cc37fc634c518b5be65cd143c9a/app/controllers/sessions_controller.rb#L19)):_

> ``` Ruby
>   def destroy
>     log_out
>     redirect_to root_url
> ```

`root_path`

---

_[app/helpers/sessions_helper.rb, line 17 at r2](https://reviewable.io:443/reviews/niedzwiedz/montekombat/3#-KS0QbUS0TUQjWvO7xND:-KS0QbUTx4pn6_MaXQO_:b3ymwxt) ([raw file](https://github.com/niedzwiedz/montekombat/blob/6b835e18f43c8cc37fc634c518b5be65cd143c9a/app/helpers/sessions_helper.rb#L17)):_

> ``` Ruby
>   def logged_in?
>     current_user.present?
>   end
> ```

it's better to move that to controller and declare helper methods there (`log_in` and `log_out` methods shouldn't be accessible from the view)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/niedzwiedz/montekombat/3)_

**Comment by Niedzwiedz** [comment]
Review status: 10 of 22 files reviewed at latest revision, 6 unresolved discussions.

---

_[config/routes.rb, line 6 at r1](https://reviewable.io:443/reviews/niedzwiedz/montekombat/3#-KRn1TjTa4MXF0cKBZjN:-KRni1nX7aJm5lki9lAd:b60ykt4) ([raw file](https://github.com/niedzwiedz/montekombat/blob/7154ff8074fe92e365a948fa92068406d59eb3d0/config/routes.rb#L6)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> why this one?
> </details>
> I get Routing Error when post for login is not present

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/niedzwiedz/montekombat/3)_

**Comment by wmaciejak** [comment]
Reviewed 1 of 8 files at r2, 11 of 13 files at r3.
Review status: 20 of 22 files reviewed at latest revision, 8 unresolved discussions.

---

_[app/controllers/users_controller.rb, line 46 at r3](https://reviewable.io:443/reviews/niedzwiedz/montekombat/3#-KS1_kAtomrFa_vLBR1u:-KS1_kAvh1MebbIZps-k:b-feu7c9) ([raw file](https://github.com/niedzwiedz/montekombat/blob/e3a3e92217e56abfb597a7facc8694ee3c4457d6/app/controllers/users_controller.rb#L46)):_

> ``` Ruby
> 
>   def destroy
>     User.find(parmas[:id]).destroy
> ```

`params`, typo ;)

---

_[app/views/layouts/application.html.slim, line 23 at r3](https://reviewable.io:443/reviews/niedzwiedz/montekombat/3#-KS1a2F4hqe463U6yksq:-KS1a2F5R5AkAYA1ZhLz:b2aqpkb) ([raw file](https://github.com/niedzwiedz/montekombat/blob/e3a3e92217e56abfb597a7facc8694ee3c4457d6/app/views/layouts/application.html.slim#L23)):_

> ``` Slim
>         | ||
>         = link_to "Login", login_path
>       - if logged_in?
> ```

Why don't you merge two `logged_in?` to one?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/niedzwiedz/montekombat/3)_

**Comment by Niedzwiedz** [comment]
Review status: 20 of 22 files reviewed at latest revision, 8 unresolved discussions.

---

_[app/controllers/sessions_controller.rb, line 19 at r2](https://reviewable.io:443/reviews/niedzwiedz/montekombat/3#-KS0R128kM8KHXBeSAPo:-KS6GyThaM_xPZEyrbzC:b-896fix) ([raw file](https://github.com/niedzwiedz/montekombat/blob/6b835e18f43c8cc37fc634c518b5be65cd143c9a/app/controllers/sessions_controller.rb#L19)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> `root_path`
> </details>
> Done.

---

_[app/controllers/users_controller.rb, line 46 at r3](https://reviewable.io:443/reviews/niedzwiedz/montekombat/3#-KS1_kAtomrFa_vLBR1u:-KS5MkbXoKk6bdtHMsRt:b-896fix) ([raw file](https://github.com/niedzwiedz/montekombat/blob/e3a3e92217e56abfb597a7facc8694ee3c4457d6/app/controllers/users_controller.rb#L46)):_
<details><summary>

<i>Previously, wojtekmaciej (Wojciech Maciejak) wrote…</i></summary>



> `params`, typo ;)
> </details>
> Done.

---

_[app/views/layouts/application.html.slim, line 23 at r3](https://reviewable.io:443/reviews/niedzwiedz/montekombat/3#-KS1a2F4hqe463U6yksq:-KS6H-KohCmHSq2pdm02:b-896fix) ([raw file](https://github.com/niedzwiedz/montekombat/blob/e3a3e92217e56abfb597a7facc8694ee3c4457d6/app/views/layouts/application.html.slim#L23)):_
<details><summary>

<i>Previously, wojtekmaciej (Wojciech Maciejak) wrote…</i></summary>



> Why don't you merge two `logged_in?` to one?
> </details>
> Done.

---

_[app/views/users/edit.html.slim, line 5 at r1](https://reviewable.io:443/reviews/niedzwiedz/montekombat/3#-KRmzbnG8z0VZzxhJqkM:-KS6H00pLxAh-ZUIxavX:b-896fix) ([raw file](https://github.com/niedzwiedz/montekombat/blob/7154ff8074fe92e365a948fa92068406d59eb3d0/app/views/users/edit.html.slim#L5)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> you're already displaying errors in matches in similar way, it would be good to move it to a partial and render it wherever errors are displayed
> </details>
> Done.

---

_[app/views/users/index.html.slim, line 20 at r1](https://reviewable.io:443/reviews/niedzwiedz/montekombat/3#-KRmzxdXGQzUGhi8dYiv:-KS6H1BT0SvB7Xz1pjBL:b-896fix) ([raw file](https://github.com/niedzwiedz/montekombat/blob/7154ff8074fe92e365a948fa92068406d59eb3d0/app/views/users/index.html.slim#L20)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> we shouldn't be able to edit other user's account
> </details>
> Done.

---

_[app/views/users/index.html.slim, line 22 at r1](https://reviewable.io:443/reviews/niedzwiedz/montekombat/3#-KRn-1_amdgrlx7TW0aj:-KS6H1jTFYhZBMpddltK:b-896fix) ([raw file](https://github.com/niedzwiedz/montekombat/blob/7154ff8074fe92e365a948fa92068406d59eb3d0/app/views/users/index.html.slim#L22)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> same with that
> </details>
> Done.

---

_[app/helpers/sessions_helper.rb, line 17 at r2](https://reviewable.io:443/reviews/niedzwiedz/montekombat/3#-KS0QbUS0TUQjWvO7xND:-KS6H2eopXBflmk2-zIn:b-896fix) ([raw file](https://github.com/niedzwiedz/montekombat/blob/6b835e18f43c8cc37fc634c518b5be65cd143c9a/app/helpers/sessions_helper.rb#L17)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> it's better to move that to controller and declare helper methods there (`log_in` and `log_out` methods shouldn't be accessible from the view)
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/niedzwiedz/montekombat/3)_

**Comment by wmaciejak** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/niedzwiedz/montekombat/3)_

**Pull request merged**
