### PR TITLE
Setting up match controller

### PR DESCRIPTION
**Pull request by Niedzwiedz**
Match controller setup and tests

---

This change is [Reviewable](https://reviewable.io/reviews/niedzwiedz/montekombat/2)

### CODE REVIEW

**Comment by jotka87** [comment]
Reviewed 21 of 22 files at r1.
Review status: 20 of 21 files reviewed at latest revision, 11 unresolved discussions.

---

_[Gemfile, line 42 at r1](https://reviewable.io:443/reviews/niedzwiedz/montekombat/2#-KRh2rahhBxFRKLlKg5g:-KRh2rahhBxFRKLlKg5h:b-171bvy) ([raw file](https://github.com/niedzwiedz/montekombat/blob/e75cfe701aa40876c0adddcb4b832dadce39acc8/Gemfile#L42)):_

> ``` Ruby
>   gem "byebug", platform: :mri
>   gem "rspec-rails"
>   gem "rails-controller-testing"
> ```

each gem should have version specified

---

_[app/controllers/matches_controller.rb, line 11 at r1](https://reviewable.io:443/reviews/niedzwiedz/montekombat/2#-KRhISuhh1LujCCeuhJf:-KRhISuhh1LujCCeuhJg:bd3a8x) ([raw file](https://github.com/niedzwiedz/montekombat/blob/e75cfe701aa40876c0adddcb4b832dadce39acc8/app/controllers/matches_controller.rb#L11)):_

> ``` Ruby
> 
>   def edit
>     @match = Match.find(params[:id])
> ```

you can think of using `before_action` for this assignment

---

_[app/controllers/matches_controller.rb, line 25 at r1](https://reviewable.io:443/reviews/niedzwiedz/montekombat/2#-KRh5mCJYRrKoqO9my6M:-KRh5mCJYRrKoqO9my6N:b-zg55cy) ([raw file](https://github.com/niedzwiedz/montekombat/blob/e75cfe701aa40876c0adddcb4b832dadce39acc8/app/controllers/matches_controller.rb#L25)):_

> ``` Ruby
>       end
>     else
>       render :new
> ```

you should also render errors so user will know what is wrong

---

_[app/controllers/matches_controller.rb, line 43 at r1](https://reviewable.io:443/reviews/niedzwiedz/montekombat/2#-KRhIjkMI7Ik0S0kotf3:-KRhIjkNpAtq19FoyCQM:b-nysfyc) ([raw file](https://github.com/niedzwiedz/montekombat/blob/e75cfe701aa40876c0adddcb4b832dadce39acc8/app/controllers/matches_controller.rb#L43)):_

> ``` Ruby
>     Match.find(params[:id]).destroy
>     flash[:success] = "Match deleted"
>     redirect_to matches_url
> ```

`matches_path`, see: http://stackoverflow.com/a/11939978

---

_[app/helpers/match_helper.rb, line 1 at r1](https://reviewable.io:443/reviews/niedzwiedz/montekombat/2#-KRhJA9R7EhhhNpj2H_E:-KRhJA9R7EhhhNpj2H_F:b5k2r9g) ([raw file](https://github.com/niedzwiedz/montekombat/blob/e75cfe701aa40876c0adddcb4b832dadce39acc8/app/helpers/match_helper.rb#L1)):_

> ``` Ruby
> module MatchHelper
> ```

will it be used? Because it's the best approach to remove auto generated files if they are not used, we don't want to have a messy repo with bunch of empty files. If you're gonna use it - that's fine, it can stay, but if not - I would remove that, it can be always added manually later.

---

_[app/views/layouts/application.html.erb, line 12 at r1](https://reviewable.io:443/reviews/niedzwiedz/montekombat/2#-KRhJnuSCFKpj29bH70i:-KRhJnuTuv0t-qg3Oxua:bt3ao9o) ([raw file](https://github.com/niedzwiedz/montekombat/blob/e75cfe701aa40876c0adddcb4b832dadce39acc8/app/views/layouts/application.html.erb#L12)):_

> ``` erb
> 
>   <body>
>       <div class="container">
> ```

incorrect indentation - one level extra, also below

---

_[app/views/matches/_form.html.slim, line 1 at r1](https://reviewable.io:443/reviews/niedzwiedz/montekombat/2#-KRhK28UYP2Mj56qRFwy:-KRhK28UYP2Mj56qRFwz:b-3i986r) ([raw file](https://github.com/niedzwiedz/montekombat/blob/e75cfe701aa40876c0adddcb4b832dadce39acc8/app/views/matches/_form.html.slim#L1)):_

> ``` Slim
> = @match.errors.full_messages.first if @match.errors.any?
> ```

why rendering only one error message?

---

_[app/views/matches/_form.html.slim, line 4 at r1](https://reviewable.io:443/reviews/niedzwiedz/montekombat/2#-KRhK7iKpUThUKd8w3uM:-KRhK7iKpUThUKd8w3uN:b-6l7140) ([raw file](https://github.com/niedzwiedz/montekombat/blob/e75cfe701aa40876c0adddcb4b832dadce39acc8/app/views/matches/_form.html.slim#L4)):_

> ``` Slim
> = form_for @match do |f|
>   |  Game: 
>   = f.select :game_id, options_from_collection_for_select(Game.all, :id, :name)
> ```

`Game.all` should be specified in the controller, view should be used only for rendering data provided by the controller

---

_[app/views/matches/index.html.slim, line 2 at r1](https://reviewable.io:443/reviews/niedzwiedz/montekombat/2#-KRhKMNqwgR2NFr3YI0A:-KRhKMNqwgR2NFr3YI0B:b-l9n9kf) ([raw file](https://github.com/niedzwiedz/montekombat/blob/e75cfe701aa40876c0adddcb4b832dadce39acc8/app/views/matches/index.html.slim#L2)):_

> ``` Slim
> h1
>   |  All Matches
> ```

extra space

---

_[spec/factories/matches.rb, line 2 at r1](https://reviewable.io:443/reviews/niedzwiedz/montekombat/2#-KRhLymD_Xv1m082DwMg:-KRhLymD_Xv1m082DwMh:b1rfy5x) ([raw file](https://github.com/niedzwiedz/montekombat/blob/e75cfe701aa40876c0adddcb4b832dadce39acc8/spec/factories/matches.rb#L2)):_

> ``` Ruby
> FactoryGirl.define do
>   factory :match_controller do |f|
> ```

in controller specs you should use match factory, that file should be removed (factories are only created for models, and they are used across all of the specs)

---

_[spec/helpers/match_helper_spec.rb, line 14 at r1](https://reviewable.io:443/reviews/niedzwiedz/montekombat/2#-KRhLCNWB_zIEPTqqOae:-KRhLCNWB_zIEPTqqOaf:bcqwyea) ([raw file](https://github.com/niedzwiedz/montekombat/blob/e75cfe701aa40876c0adddcb4b832dadce39acc8/spec/helpers/match_helper_spec.rb#L14)):_

> ``` Ruby
> # end
> RSpec.describe MatchHelper, type: :helper do
>   pending "add some examples to (or delete) #{__FILE__}"
> ```

similar comment as for `match_helper`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/niedzwiedz/montekombat/2)_

**Comment by Niedzwiedz** [comment]
Review status: 11 of 26 files reviewed at latest revision, 11 unresolved discussions.

---

_[app/views/matches/_form.html.slim, line 4 at r1](https://reviewable.io:443/reviews/niedzwiedz/montekombat/2#-KRhK7iKpUThUKd8w3uM:-KRhpnxS45ELu80WqWNQ:bkjfykc) ([raw file](https://github.com/niedzwiedz/montekombat/blob/e75cfe701aa40876c0adddcb4b832dadce39acc8/app/views/matches/_form.html.slim#L4)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> `Game.all` should be specified in the controller, view should be used only for rendering data provided by the controller
> </details>
> it acts weird with @games and @teams from controller: Throws:
> "undefined method `map' for nil:NilClass
> Did you mean?  tap"
> when i try to create match with invalid params.
> That's not the case when I use Game.all.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/niedzwiedz/montekombat/2)_

**Comment by jotka87** [comment]
Reviewed 16 of 17 files at r2.
Review status: 25 of 26 files reviewed at latest revision, 10 unresolved discussions.

---

_[app/controllers/application_controller.rb, line 6 at r2](https://reviewable.io:443/reviews/niedzwiedz/montekombat/2#-KRi9wJ_sOXCHxgeC-Cv:-KRi9wJakTyccUjJT6lq:b-nmgtnk) ([raw file](https://github.com/niedzwiedz/montekombat/blob/a1d7b762313be4e0682f176f31e1343dffa96baa/app/controllers/application_controller.rb#L6)):_

> ``` Ruby
>   rescue_from ActiveRecord::RecordNotFound, with: :render_four_o_four
> 
>   def render_four_o_four
> ```

I'm not sure about that name ;p maybe `render_not_found`?

---

_[app/views/matches/_form.html.slim, line 1 at r2](https://reviewable.io:443/reviews/niedzwiedz/montekombat/2#-KRiAbt6Q0FfTQuDfq7A:-KRiAbt6Q0FfTQuDfq7B:bm78zd) ([raw file](https://github.com/niedzwiedz/montekombat/blob/a1d7b762313be4e0682f176f31e1343dffa96baa/app/views/matches/_form.html.slim#L1)):_

> ``` Slim
> = @match.errors.full_messages if @match.errors.any?
> ```

each error should be rendered separately

---

_[spec/controllers/matches_controller_spec.rb, line 8 at r2](https://reviewable.io:443/reviews/niedzwiedz/montekombat/2#-KRiAo7Y5CwjJf9_BiNd:-KRiAo7ZPsHtmuRv5yup:betxnz5) ([raw file](https://github.com/niedzwiedz/montekombat/blob/a1d7b762313be4e0682f176f31e1343dffa96baa/spec/controllers/matches_controller_spec.rb#L8)):_

> ``` Ruby
>     before do
>       get :index
>     end
> ```

make a one-liner out of it: `before { get :index }`
The general rule is - if a block consists of a single line and one-liner doesn't exceed the length of 100 chars it should be one-liner

---

_[spec/controllers/matches_controller_spec.rb, line 47 at r2](https://reviewable.io:443/reviews/niedzwiedz/montekombat/2#-KRiCPVbtW7vnusam6Ja:-KRiCDvGShXUaab9Ghiu:b-co5l6a) ([raw file](https://github.com/niedzwiedz/montekombat/blob/a1d7b762313be4e0682f176f31e1343dffa96baa/spec/controllers/matches_controller_spec.rb#L47)):_

> ``` Ruby
>     end
>     context "with valid attributes" do
>       # let(:match) { build(:match) }
> ```

why not let?

---

_[spec/controllers/matches_controller_spec.rb, line 51 at r2](https://reviewable.io:443/reviews/niedzwiedz/montekombat/2#-KRiCUF6HyqxTn8U6lRI:-KRiCUF6HyqxTn8U6lRJ:bufrp32) ([raw file](https://github.com/niedzwiedz/montekombat/blob/a1d7b762313be4e0682f176f31e1343dffa96baa/spec/controllers/matches_controller_spec.rb#L51)):_

> ``` Ruby
>         @match = build(:match)
>       end
>       it { expect { subject }.to change{ Match.count }.by(1) }
> ```

method and a block passed to it should be separated by a single space:
`change { Match.count }`

---

_[spec/controllers/matches_controller_spec.rb, line 101 at r2](https://reviewable.io:443/reviews/niedzwiedz/montekombat/2#-KRiBFMALYTtY8dMDOhg:-KRiBFMALYTtY8dMDOhh:binowgy) ([raw file](https://github.com/niedzwiedz/montekombat/blob/a1d7b762313be4e0682f176f31e1343dffa96baa/spec/controllers/matches_controller_spec.rb#L101)):_

> ``` Ruby
>   describe "DELETE #destroy" do
>     before do
>       binding.pry
> ```

never commit `binding.pry`

---

_[spec/factories/matches.rb, line 2 at r1](https://reviewable.io:443/reviews/niedzwiedz/montekombat/2#-KRhLymD_Xv1m082DwMg:-KRiDTMIxzxwdOLVI1yK:b-9kmwqw) ([raw file](https://github.com/niedzwiedz/montekombat/blob/e75cfe701aa40876c0adddcb4b832dadce39acc8/spec/factories/matches.rb#L2)):_
<details><summary>

<i>Previously, jotka87 (Kamila Straus) wrote…</i></summary>



> in controller specs you should use match factory, that file should be removed (factories are only created for models, and they are used across all of the specs)
> </details>
> no no no, you already have a factory for match, this file is redundant, please remove it.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/niedzwiedz/montekombat/2)_

**Comment by jotka87** [comment]
Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[app/controllers/matches_controller.rb, line 4 at r3](https://reviewable.io:443/reviews/niedzwiedz/montekombat/2#-KRlvP3ZKfWssBWE0PiN:-KRlvP3_CajP6shhoIT0:b-1y1c4a) ([raw file](https://github.com/niedzwiedz/montekombat/blob/71e639256693b1624e4c52851d7bdd4136ac7d80/app/controllers/matches_controller.rb#L4)):_

> ``` Ruby
>   before_action :set_match, only: [:show, :edit, :update]
>   def index
>     @matches = Match.includes(:game, :team_1, :team_2).all
> ```

`all` is unnecessary

---

_[spec/controllers/matches_controller_spec.rb, line 87 at r3](https://reviewable.io:443/reviews/niedzwiedz/montekombat/2#-KRlw3tieoKqTGfGTGRS:-KRlw3tieoKqTGfGTGRT:bx2ap25) ([raw file](https://github.com/niedzwiedz/montekombat/blob/71e639256693b1624e4c52851d7bdd4136ac7d80/spec/controllers/matches_controller_spec.rb#L87)):_

> ``` Ruby
> 
>   describe "DELETE #destroy" do
>     before { @match = create(:match) }
> ```

use let

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/niedzwiedz/montekombat/2)_

**Comment by jotka87** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/niedzwiedz/montekombat/2)_

**Pull request merged**
